version: 1
app_name: strategy
connections:
  - config: !JavaScript
     bootstrap_path: ./ingest_price.js
    name: price_connection

sources:
  - name: price
    table_name: json_records
    connection: price_connection

endpoints:
  - name: price
    table_name: price
    path: /price

  - name: indicators
    table_name: indicators
    path: /indicators

lambdas:
  - !JavaScript
    endpoint: indicators
    module: ./strategies_runner.ts

sql:
    SELECT obv(value) as value INTO indicators FROM price;

udfs:
  - name: obv
    config: !JavaScript
      module: ./indicators/obv.ts