app_name: trading
version: 1

connections:
  - config : !LocalStorage
      details:
        path: ./history
      tables:
        - !Table
          name: prices
          config: !CSV
            path: prices
            extension: .csv
    name: prices
#  - config: !JavaScript
#      module: ./common/buy_now_sell_after_10_days.ts
#    name: actions

endpoints:
- name: prices
  path: /prices
  table_name: prices


lambdas:
  - !JavaScript
    endpoint: prices
    module: ./common/buy_now_sell_after_10_days.ts