version: 1
app_name: strategy
connections:
  - config: !JavaScript
     bootstrap_path: ./ingest_price.js
    name: price_connection

sources:
  - name: price
    table_name: json_records
    connection: price_connection

endpoints:
  - name: price
    table_name: price
    path: /price

lambdas:
  - !JavaScript
    endpoint: price
    module: ./strategies/obv.ts
