version: 1
app_name: strategy
connections:
  - config: !JavaScript
     bootstrap_path: ./ingest_price.js
    name: price_connection

sources:
  - name: price
    table_name: json_records
    connection: price_connection

endpoints:
  - name: price
    table_name: price
    path: /price

  - name: indicators
    table_name: indicators
    path: /indicators
    index:
      secondary:
        create:
        - !SortedInverted
          fields:
          - ticker

lambdas:
  - !JavaScript
    endpoint: indicators
    module: ./common/strategies_runner.ts

sql: |
  SELECT 
    JSON_VALUE(value, '$.time') AS time,
    JSON_VALUE(value, '$.ticker') AS ticker,
    JSON_VALUE(value, '$.price_in_dollar') AS price,
    obv(value) as obv,
    ma12(value) as ma12
  INTO indicators 
  FROM price;

udfs:
  - name: obv
    config: !JavaScript
      module: ./indicators/obv.ts
  - name: ma12
    config: !JavaScript
      module: ./indicators/ma12.ts
