app_name: trading
version: 1
api:
  app_grpc:
    port: 50153
  rest:
    port:
      9080
  grpc:
    port:
      50151
  sql:
    port:
      9999

connections:
- name: actions
  config: !Grpc
    host: 0.0.0.0
    port: 12345
    adapter: default
    schemas: !Path actions.json

endpoints:
- name: actions
  path: /actions
  table_name: actions
