app_name: trading
version: 1
api:
  app_grpc:
    port: 50153
  rest:
    port:
      9080
  grpc:
    port:
      50151
  sql:
    port:
      9999

connections:
- name: actions
  config: !Grpc
    host: 0.0.0.0
    port: 12345
    adapter: default
    schemas: !Path actions.json

operators:
- name: trade
  config: !JavaScript
    schema:
      fields:
      - name: strategy
        typ: String
        nullable: false
      - name: time
        typ: Timestamp
        nullable: false
      - name: cash_in_dollar
        typ: Float
        nullable: false
      - name: asset_value_in_dollar
        typ: Float
        nullable: false
    module: ./trade.ts

sql: SELECT * INTO net_worth from trade(actions);

endpoints:
- name: actions
  path: /actions
  table_name: actions
  index:
    secondary:
      create:
        - !SortedInverted
          fields:
            - action
            - ticker

- name: net_worth
  path: /net_worth
  table_name: net_worth
